# Generated by Django 4.2 on 2024-01-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertcanal',
            name='name_code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
