# Generated by Django 4.2 on 2024-05-11 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_shared', '0002_arrondissement_name_code_department_name_code_and_more'),
        ('UserManagement', '0005_organisationtype_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_fiche', models.CharField(default='', max_length=255)),
                ('date_reception', models.DateTimeField()),
                ('date_constat', models.DateTimeField()),
                ('village', models.CharField(default='', max_length=255)),
                ('title_exploitation', models.CharField(default='', max_length=255)),
                ('exploitant_name', models.CharField(default='', max_length=255)),
                ('infraction_description', models.TextField(default='')),
                ('soupicious_infraction', models.TextField(default='')),
                ('ref_legislation_text', models.TextField(default='')),
                ('state', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrondissement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_shared.arrondissement')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_shared.department')),
                ('observator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement.userprofile')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement.organisation')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_shared.region')),
            ],
        ),
        migrations.CreateModel(
            name='FichePertinence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_fiche', models.CharField(default='', max_length=255)),
                ('date_renseignement', models.DateTimeField()),
                ('date_demarage', models.DateTimeField()),
                ('contexte', models.TextField(default='')),
                ('domain', models.CharField(default='', max_length=255)),
                ('designation', models.TextField(default='')),
                ('pertinence', models.CharField(default='', max_length=255)),
                ('access_site', models.CharField(default='', max_length=255)),
                ('activity_state', models.CharField(default='', max_length=255)),
                ('state', models.CharField(default='', max_length=255)),
                ('justif', models.CharField(default='', max_length=255)),
                ('nature', models.CharField(default='', max_length=255)),
                ('severity_level', models.CharField(default='', max_length=255)),
                ('severity_justif', models.CharField(default='', max_length=255)),
                ('profit_level', models.CharField(default='', max_length=255)),
                ('sign_resp', models.ImageField(upload_to='signatures/')),
                ('sign_coor', models.ImageField(upload_to='signatures/')),
                ('sign_obs', models.ImageField(upload_to='signatures/')),
                ('date_sign_resp', models.DateTimeField()),
                ('date_sign_coo', models.DateTimeField()),
                ('date_sign_obs', models.DateTimeField()),
                ('observation_coor', models.TextField(default='')),
                ('observation_resp', models.TextField(default='')),
                ('priority', models.CharField(default='', max_length=255)),
                ('status', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator', to='UserManagement.userprofile')),
                ('fiche_information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FicheManagement.ficheinformation')),
                ('observator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observator', to='UserManagement.userprofile')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable', to='UserManagement.userprofile')),
            ],
        ),
    ]
