# Generated by Django 4.2 on 2024-05-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FicheManagement', '0002_ficheinformation_entite'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheinformation',
            name='sign_obs',
            field=models.ImageField(default='', upload_to='signatures/'),
            preserve_default=False,
        ),
    ]
