# Generated by Django 4.2 on 2024-05-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FicheManagement', '0003_ficheinformation_sign_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheinformation',
            name='sign_obs',
            field=models.BinaryField(),
        ),
    ]
