# Generated by Django 4.2 on 2024-05-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FicheManagement', '0005_alter_fichepertinence_pertinence'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichepertinence',
            name='denonciateur',
            field=models.CharField(default='', max_length=255),
        ),
    ]
