# Generated by Django 4.2 on 2024-05-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FicheManagement', '0006_fichepertinence_denonciateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichepertinence',
            name='date_demarage',
            field=models.DateTimeField(null=True),
        ),
    ]
