# Generated by Django 4.2 on 2024-05-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FicheManagement', '0007_alter_fichepertinence_date_demarage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichepertinence',
            name='pertinence',
            field=models.BooleanField(default=False),
        ),
    ]
