# Generated by Django 4.2 on 2024-05-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FicheManagement', '0008_alter_fichepertinence_pertinence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichepertinence',
            name='date_sign_coo',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fichepertinence',
            name='date_sign_obs',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fichepertinence',
            name='date_sign_resp',
            field=models.DateTimeField(null=True),
        ),
    ]
