# Generated by Django 4.2 on 2024-05-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FicheManagement', '0009_alter_fichepertinence_date_sign_coo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichepertinence',
            name='arret_activite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichepertinence',
            name='encours_activite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichepertinence',
            name='niveau',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichepertinence',
            name='niveauSeverite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichepertinence',
            name='access_site',
            field=models.BooleanField(default=False),
        ),
    ]
