# Generated by Django 4.2 on 2024-06-05 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0007_alter_userprofile_firstname_and_more'),
        ('FicheManagement', '0011_alter_ficheinformation_sign_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichepertinence',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement.organisation'),
        ),
    ]
