# Generated by Django 4.2 on 2024-06-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FicheManagement', '0012_fichepertinence_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichepertinence',
            name='niveauSeverite',
            field=models.IntegerField(default=False),
        ),
    ]
