# Generated by Django 4.2 on 2024-06-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FicheManagement', '0013_alter_fichepertinence_niveauseverite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichepertinence',
            name='justif',
            field=models.BooleanField(default=False),
        ),
    ]
