# Generated by Django 4.2 on 2024-06-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FicheManagement', '0014_alter_fichepertinence_justif'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheinformation',
            name='date_sign_coord',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ficheinformation',
            name='date_sign_obs',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ficheinformation',
            name='date_sign_resp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ficheinformation',
            name='sign_coord',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ficheinformation',
            name='sign_resp',
            field=models.TextField(default=''),
        ),
    ]
