# Generated by Django 4.2 on 2024-06-10 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0007_alter_userprofile_firstname_and_more'),
        ('FicheManagement', '0015_ficheinformation_date_sign_coord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheinformation',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fi_coord', to='UserManagement.userprofile'),
        ),
        migrations.AddField(
            model_name='ficheinformation',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fi_res', to='UserManagement.userprofile'),
        ),
    ]
