# Generated by Django 4.2 on 2024-06-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FicheManagement', '0016_ficheinformation_coordinator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichepertinence',
            name='sign_coor',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='fichepertinence',
            name='sign_obs',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='fichepertinence',
            name='sign_resp',
            field=models.TextField(default=''),
        ),
    ]
