# Generated by Django 4.2 on 2024-06-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FicheManagement', '0017_alter_fichepertinence_sign_coor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichepertinence',
            name='priority',
            field=models.TextField(default=''),
        ),
    ]
