# Generated by Django 4.2 on 2024-01-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_alter_userprofile_active_alter_userprofile_isarchive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='name_code',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
