# Generated by Django 4.2 on 2024-01-14 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0004_organisationtype_remove_organisation_category_osc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisationtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
