# Generated by Django 4.2 on 2024-05-27 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FicheManagement', '0010_fichepertinence_arret_activite_and_more'),
        ('UserManagement', '0005_organisationtype_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('pv_entretient', models.FileField(upload_to='mission_doc')),
                ('compte_rendu_entretient', models.FileField(upload_to='mission_doc')),
                ('check_list_conformite', models.FileField(upload_to='mission_doc')),
                ('rapport_mission', models.FileField(upload_to='mission_doc')),
                ('fiche_observation', models.FileField(upload_to='mission_doc')),
                ('draft_tdr', models.FileField(upload_to='mission_doc')),
                ('tdr_valid', models.FileField(upload_to='mission_doc')),
                ('ordre_mission', models.FileField(upload_to='mission_doc')),
                ('tdr_amender', models.FileField(upload_to='mission_doc')),
                ('statut_mission', models.CharField(default='', max_length=255)),
                ('rapport_mission_approuve', models.FileField(upload_to='mission_doc')),
                ('rapport_mission_amende_2', models.FileField(upload_to='mission_doc')),
                ('rapport_mission_amende_1', models.FileField(upload_to='mission_doc')),
                ('plan_lobbying', models.FileField(upload_to='mission_doc')),
                ('rapport_mission_commente', models.TextField(default='')),
                ('comment_cancel', models.TextField(default='')),
                ('motif_annulation', models.TextField(default='')),
                ('statut_commentaire', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiche_information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FicheManagement.ficheinformation')),
                ('fiche_pertinence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FicheManagement.fichepertinence')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement.organisation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement.userprofile')),
            ],
        ),
    ]
