# Generated by Django 4.2 on 2024-06-13 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0007_alter_userprofile_firstname_and_more'),
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='date_check_list',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='date_compte_rendu_entretien',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='date_draft_tdr',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='date_fiche_observation',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='date_mission_amende_1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='date_mission_amende_2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='date_mission_approuve',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='date_mission_commente',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='date_ordre_mission',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='date_plan_lobbying',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='date_pv_entretien',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='date_rapport_mission',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='date_tdr_amender',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='date_tdr_valid',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='user_check_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_list', to='UserManagement.userprofile'),
        ),
        migrations.AddField(
            model_name='mission',
            name='user_compte_rendu_entretien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compte_rendu_entretien', to='UserManagement.userprofile'),
        ),
        migrations.AddField(
            model_name='mission',
            name='user_draft_tdr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_tdr', to='UserManagement.userprofile'),
        ),
        migrations.AddField(
            model_name='mission',
            name='user_fiche_observation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiche_observation', to='UserManagement.userprofile'),
        ),
        migrations.AddField(
            model_name='mission',
            name='user_mission_amende_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapport_mission_amende_1', to='UserManagement.userprofile'),
        ),
        migrations.AddField(
            model_name='mission',
            name='user_mission_amende_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapport_mission_amende_2', to='UserManagement.userprofile'),
        ),
        migrations.AddField(
            model_name='mission',
            name='user_mission_approuve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapport_mission_approuve', to='UserManagement.userprofile'),
        ),
        migrations.AddField(
            model_name='mission',
            name='user_mission_commente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapport_mission_commente', to='UserManagement.userprofile'),
        ),
        migrations.AddField(
            model_name='mission',
            name='user_ordre_mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordre_mission', to='UserManagement.userprofile'),
        ),
        migrations.AddField(
            model_name='mission',
            name='user_plan_lobbying',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_lobbying', to='UserManagement.userprofile'),
        ),
        migrations.AddField(
            model_name='mission',
            name='user_pv_entretien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pv_entretien', to='UserManagement.userprofile'),
        ),
        migrations.AddField(
            model_name='mission',
            name='user_rapport_mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapport_mission', to='UserManagement.userprofile'),
        ),
        migrations.AddField(
            model_name='mission',
            name='user_tdr_amender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tdr_amender', to='UserManagement.userprofile'),
        ),
        migrations.AddField(
            model_name='mission',
            name='user_tdr_valid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tdr_valid', to='UserManagement.userprofile'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='rapport_mission_commente',
            field=models.FileField(upload_to='mission_doc'),
        ),
    ]
