# Generated by Django 4.2 on 2024-07-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_mission_date_check_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='date_mission_cancel',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='date_mission_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='date_mission_start',
            field=models.DateTimeField(null=True),
        ),
    ]
