# Generated by Django 4.2 on 2024-07-08 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0007_alter_userprofile_firstname_and_more'),
        ('mission', '0003_mission_date_mission_cancel_mission_date_mission_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='user_cancel_mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancel_mission', to='UserManagement.userprofile'),
        ),
        migrations.AddField(
            model_name='mission',
            name='user_end_mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_mission', to='UserManagement.userprofile'),
        ),
        migrations.AddField(
            model_name='mission',
            name='user_start_mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_mission', to='UserManagement.userprofile'),
        ),
    ]
