# Generated by Django 4.2 on 2024-07-08 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0007_alter_userprofile_firstname_and_more'),
        ('mission', '0004_mission_user_cancel_mission_mission_user_end_mission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='assign_organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_mission', to='UserManagement.organisation'),
        ),
    ]
