# Generated by Django 4.2 on 2024-07-20 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FicheManagement', '0018_alter_fichepertinence_priority'),
        ('mission', '0005_mission_assign_organisation'),
        ('AlertsManagement', '0002_alertcanal_name_code'),
        ('UserAction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='alert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AlertsManagement.alert'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='ficheInformation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FicheManagement.ficheinformation'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='fichePertinence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FicheManagement.fichepertinence'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mission.mission'),
        ),
    ]
