# Generated by Django 4.2 on 2024-07-20 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0007_alter_userprofile_firstname_and_more'),
        ('UserAction', '0002_useraction_alert_useraction_ficheinformation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement.userprofile'),
        ),
    ]
